name: Ejecutar Script

on:
  schedule:
    - cron: "0 10 * * 2,4"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ejecutar script
        run: |
          python neumaticos (1).ipynb
